namespace FoodDelivery.Api.Models;

/// <summary>
/// Represents a summary of order metrics for the dashboard.
/// </summary>
public class DashboardSummaryDto
{
    /// <summary>
    /// Gets or sets the total number of orders.
    /// </summary>
    public int TotalOrders { get; set; }

    /// <summary>
    /// Gets or sets the number of orders currently in the Placed status.
    /// </summary>
    public int PlacedOrders { get; set; }

    /// <summary>
    /// Gets or sets the number of orders currently in the Preparing status.
    /// </summary>
    public int PreparingOrders { get; set; }

    /// <summary>
    /// Gets or sets the number of orders currently in the OutForDelivery status.
    /// </summary>
    public int OutForDeliveryOrders { get; set; }

    /// <summary>
    /// Gets or sets the number of orders currently in the Delivered status.
    /// </summary>
    public int DeliveredOrders { get; set; }

    /// <summary>
    /// Gets or sets the number of orders currently in the Cancelled status.
    /// </summary>
    public int CancelledOrders { get; set; }

    /// <summary>
    /// Gets or sets the total revenue generated by all orders.
    /// </summary>
    public decimal TotalRevenue { get; set; }
}
